# Generated by Django 3.2.8 on 2021-10-22 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Userprofile', '0001_initial'),
        ('Businessprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='Userprofiles',
            field=models.ManyToManyField(related_name='userprofiles', to='Userprofile.Userprofile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
