# Generated by Django 3.2.8 on 2021-10-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userprofile', '0001_initial'),
        ('Businessprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='Userprofiles',
            field=models.ManyToManyField(blank=True, related_name='businessprofiles', to='Userprofile.Userprofile'),
        ),
    ]
