# Generated by Django 3.2.8 on 2021-10-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Businessprofile', '0003_auto_20211025_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
