# Generated by Django 3.2.8 on 2021-10-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0002_auto_20211025_1035'),
        ('Businessprofile', '0004_auto_20211025_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='Userprofiles',
            field=models.ManyToManyField(blank=True, related_name='businessprofiles', to='Userprofile.Userprofile'),
        ),
    ]
