# Generated by Django 3.2.8 on 2021-10-25 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Businessprofile', '0005_alter_businessprofile_userprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
