# Generated by Django 3.2.8 on 2021-10-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobrole', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobrole',
            old_name='name',
            new_name='jobrole',
        ),
    ]
