# Generated by Django 3.2.8 on 2021-10-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_alter_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
