# Generated by Django 3.2.8 on 2021-10-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Businessprofile', '0005_alter_businessprofile_userprofiles'),
        ('Jobpost', '0002_alter_jobpost_jobrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='Businessprofile.businessprofile'),
        ),
    ]
