# Generated by Django 3.2.8 on 2021-10-25 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobrole', '0002_rename_name_jobrole_jobrole'),
        ('Jobpost', '0003_auto_20211025_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='jobrole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobposts', to='Jobrole.jobrole'),
        ),
    ]
