# Generated by Django 3.2.8 on 2021-10-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0003_alter_userprofile_businessprofile'),
        ('Jobpost', '0004_alter_jobpost_jobrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='Userprofiles',
            field=models.ManyToManyField(blank=True, related_name='jobposts', to='Userprofile.Userprofile'),
        ),
    ]
