# Generated by Django 3.2.8 on 2021-10-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0003_alter_userprofile_businessprofile'),
        ('Busrating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busrating',
            name='userprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businessratings', to='Userprofile.userprofile'),
        ),
    ]
