# Generated by Django 3.2.8 on 2021-10-24 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Businessprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('location', models.CharField(default=None, max_length=300)),
                ('cover_letter', models.TextField(default=None, max_length=3000)),
                ('cv', models.TextField(default=None, max_length=3000)),
                ('head_shot', models.TextField(default=None, max_length=100)),
                ('Businessprofile', models.ManyToManyField(blank=True, related_name='businesses', to='Businessprofile.Businessprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
