# Generated by Django 3.2.8 on 2021-10-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Businessprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default=None, max_length=50)),
                ('lastname', models.CharField(default=None, max_length=50)),
                ('location', models.CharField(default=None, max_length=300)),
                ('coverletter', models.TextField(default=None, max_length=3000)),
                ('cv', models.TextField(default=None, max_length=3000)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('Businessprofile', models.ManyToManyField(blank=True, related_name='userprofiles', to='Businessprofile.Businessprofile')),
            ],
        ),
    ]
