# Generated by Django 3.2.8 on 2021-10-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cover_letter',
            new_name='coverletter',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
