# Generated by Django 3.2.8 on 2021-10-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Businessprofile', '0005_alter_businessprofile_userprofiles'),
        ('Userprofile', '0002_auto_20211025_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Businessprofile',
            field=models.ManyToManyField(blank=True, related_name='userprofiles', to='Businessprofile.Businessprofile'),
        ),
    ]
