# Generated by Django 3.2.8 on 2021-10-25 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Businessprofile', '0005_alter_businessprofile_userprofiles'),
        ('Empreview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreview',
            name='businessprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employeereviews', to='Businessprofile.businessprofile'),
        ),
    ]
